### GET kõik matkad
GET http://localhost:8085/api/matk
content-type: application/json
### GET üks matk ID järgi ID ON VIGANE 
GET http://localhost:8085/api/matk/56xsd
    content-type: application/json
### GET üks matk ID järgi (veel üks näide)
GET http://localhost:8085/api/matk/2
content-type: application/json
### POST lisa matk
POST http://localhost:8085/api/matk
Content-Type: application/json

{
    "nimetus": "Talvematk Soomaal",
    "kirjeldus": "Suusatame läbi lumise Soomaa rahvuspargi ja nautime talvise looduse ilu",
    "pildiUrl": "/assets/Hiker.png"
}

### GET kõik uudised
GET http://localhost:8085/api/uudised

### DELETE üks matk ID järgi
DELETE http://localhost:8085/api/matk/1
content-type: application/json


### MAtka kõik osalejad
GET http://localhost:8085/api/matk/1/osalejad
content-type: application/json

### ühe osaleja lisamine
POST http://localhost:8085/api/matk/1/osalejad
Content-Type: application/json

{
    "nimi": "Märt",
    "email": "märt@matkaja.ee"
}
### Matka muutmine
PATCH http://localhost:8085/api/matk/1
Content-Type: application/json

{   
    "osalejad": [],
    "nimetus": "UUS NIMI"
}    
###Kogu matka info 
GET http://localhost:8085/api/matk/1
content-type: application/json  